name: exemplo

on:
    pull_request:
        branches: 
          - main
          - develop
        types:
          - opened
          - reopened
jobs:
    build:
        runs-on: ubuntu:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: jdk
              uses: actions/setup-java@v4
              with: 
                distribution: 'temurin'
                java-version: '17'
            - name: build maven
              run: mvn -B package -DskipTests
        