name: exemplo

on:
  pull_request:
    branches: 
      - main
      - develop
    types:
      - opened 
      - reopened
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: jdk
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '17'
      - name: build maven
        run: mvn -B package -DskipTests
  docker:
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - name: QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: docker buildx
        uses: docker/setup-buildx-action@v3
      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jgmatosmota/cicd:1.0